// This file is automatically generated.
use cpp_core::{CastInto, Ptr};
use qt_core::{QBox, QPtr};
use qt_ui_tools::QUiLoader;
use qt_widgets::*;

#[derive(Debug)]
pub struct MainWindow {
    pub widget: QBox<QMainWindow>,
    pub centralwidget: QPtr<QWidget>,
    pub horizontal_layout_2: QPtr<QHBoxLayout>,
    pub vertical_layout: QPtr<QVBoxLayout>,
    pub list_widget: QPtr<QListWidget>,
    pub horizontal_layout: QPtr<QHBoxLayout>,
    pub btn_modify_bingli: QPtr<QPushButton>,
    pub btn_quit: QPtr<QPushButton>,
    pub menubar: QPtr<QMenuBar>,
    pub statusbar: QPtr<QStatusBar>,
}
impl MainWindow {
    pub fn load<P: CastInto<Ptr<QWidget>>>(parent: P) -> Self {
        unsafe {
            let loader = QUiLoader::new_0a();
            loader.set_language_change_enabled(true);
            let bytes = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r<ui version=\"4.0\">\r<class>MainWindow</class>\r<widget class=\"QMainWindow\" name=\"MainWindow\">\r<property name=\"geometry\">\r<rect>\r<x>0</x>\r<y>0</y>\r<width>800</width>\r<height>600</height>\r</rect>\r</property>\r<property name=\"windowTitle\">\r<string>MainWindow</string>\r</property>\r<widget class=\"QWidget\" name=\"centralwidget\">\r<layout class=\"QHBoxLayout\" name=\"horizontalLayout_2\">\r<item>\r<layout class=\"QVBoxLayout\" name=\"verticalLayout\">\r<item>\r<widget class=\"QListWidget\" name=\"listWidget\"/>\r</item>\r<item>\r<layout class=\"QHBoxLayout\" name=\"horizontalLayout\">\r<item>\r<spacer name=\"horizontalSpacer\">\r<property name=\"orientation\">\r<enum>Qt::Horizontal</enum>\r</property>\r<property name=\"sizeHint\" stdset=\"0\">\r<size>\r<width>40</width>\r<height>20</height>\r</size>\r</property>\r</spacer>\r</item>\r<item>\r<widget class=\"QPushButton\" name=\"btnModifyBingli\">\r<property name=\"text\">\r<string>添加项目进列表</string>\r</property>\r</widget>\r</item>\r<item>\r<widget class=\"QPushButton\" name=\"btnQuit\">\r<property name=\"text\">\r<string>退出</string>\r</property>\r</widget>\r</item>\r</layout>\r</item>\r</layout>\r</item>\r</layout>\r</widget>\r<widget class=\"QMenuBar\" name=\"menubar\">\r<property name=\"geometry\">\r<rect>\r<x>0</x>\r<y>0</y>\r<width>800</width>\r<height>22</height>\r</rect>\r</property>\r</widget>\r<widget class=\"QStatusBar\" name=\"statusbar\"/>\r</widget>\r<resources/>\r<connections/>\r</ui>\r".as_bytes();
            let widget = loader.load_bytes_with_parent(bytes, parent);
            assert!(!widget.is_null(), "invalid ui file");
            Self {
                centralwidget: widget.find_child("centralwidget").unwrap(),
                horizontal_layout_2: widget.find_child("horizontalLayout_2").unwrap(),
                vertical_layout: widget.find_child("verticalLayout").unwrap(),
                list_widget: widget.find_child("listWidget").unwrap(),
                horizontal_layout: widget.find_child("horizontalLayout").unwrap(),
                btn_modify_bingli: widget.find_child("btnModifyBingli").unwrap(),
                btn_quit: widget.find_child("btnQuit").unwrap(),
                menubar: widget.find_child("menubar").unwrap(),
                statusbar: widget.find_child("statusbar").unwrap(),
                widget: QBox::from_q_ptr(widget.into_q_ptr().dynamic_cast()),
            }
        }
    }
}
